# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    sudo apt-get update
    sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip
    pip install --upgrade pip
    pip install blobxfer
  displayName: 'Run a multi-line script'
