# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip
    sudo python3 -m pip install --upgrade pip
    sudo pip3 install setuptools wheel
    sudo pip3 install blobxfer
    blobxfer upload --storage-account adaptivecardstemplates --sas "$(storage_sas)" --local-path ./templates --remote-path templates --skip-on-lmt-ge
  displayName: 'Install blobxfer'